package _const

const CREATE_WALLET_FAILED = "CREATE_WALLET_FAILED"

const USER_NOT_FOUND = "USER_NOT_FOUND"

const RESULTS_WALLET_NOT_FOUND = "RESULTS_WALLET_NOT_FOUND"

const DELETE_WALLET_NOT_FOUND = "DELETE_WALLET_NOT_FOUND"

const DELETE_WALLET_FAILED = "DELETE_WALLET_FAILED"

const DELETE_WALLET_BALANCE_NOT_ZERO = "DELETE_WALLET_BALANCE_NOT_ZERO"

const RESULTS_TRANSACTIONS_NOT_FOUND = "RESULTS_TRANSACTIONS_NOT_FOUND"

const CREATE_TRANSACTION_FAILED = "CREATE_TRANSACTION_FAILED"

const WALLET_NOT_FOUND = "WALLET_NOT_FOUND"

const ACCOUNT_DEACTIVE = "ACCOUNT_DEACTIVE"

const UPDATE_EMAIL_FAILED = "UPDATE_EMAIL_FAILED"
